/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { B2bSubmissionGogetaWhereInput } from "./B2bSubmissionGogetaWhereInput";
import { IsOptional, ValidateNested, IsInt } from "class-validator";
import { Type } from "class-transformer";
import { B2bSubmissionGogetaOrderByInput } from "./B2bSubmissionGogetaOrderByInput";

@ArgsType()
class B2bSubmissionGogetaFindManyArgs {
  @ApiProperty({
    required: false,
    type: () => B2bSubmissionGogetaWhereInput,
  })
  @IsOptional()
  @ValidateNested()
  @Field(() => B2bSubmissionGogetaWhereInput, { nullable: true })
  @Type(() => B2bSubmissionGogetaWhereInput)
  where?: B2bSubmissionGogetaWhereInput;

  @ApiProperty({
    required: false,
    type: [B2bSubmissionGogetaOrderByInput],
  })
  @IsOptional()
  @ValidateNested({ each: true })
  @Field(() => [B2bSubmissionGogetaOrderByInput], { nullable: true })
  @Type(() => B2bSubmissionGogetaOrderByInput)
  orderBy?: Array<B2bSubmissionGogetaOrderByInput>;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsOptional()
  @IsInt()
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  skip?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsOptional()
  @IsInt()
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  take?: number;
}

export { B2bSubmissionGogetaFindManyArgs as B2bSubmissionGogetaFindManyArgs };
