/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringFilter } from "../../util/StringFilter";
import { Type } from "class-transformer";
import { IsOptional, IsEnum } from "class-validator";
import { EnumB2bSubmissionGogetaStatus } from "./EnumB2bSubmissionGogetaStatus";

@InputType()
class B2bSubmissionGogetaWhereInput {
  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    enum: EnumB2bSubmissionGogetaStatus,
  })
  @IsEnum(EnumB2bSubmissionGogetaStatus)
  @IsOptional()
  @Field(() => EnumB2bSubmissionGogetaStatus, {
    nullable: true,
  })
  status?:
    | "Option1"
    | "Asdasdsdasd"
    | "Asdasd"
    | "Asasd"
    | "Asd"
    | "Newoptionset";
}

export { B2bSubmissionGogetaWhereInput as B2bSubmissionGogetaWhereInput };
