/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { EnumB2bSubmissionGogetaStatus } from "./EnumB2bSubmissionGogetaStatus";
import { IsEnum, IsOptional } from "class-validator";

@InputType()
class B2bSubmissionGogetaCreateInput {
  @ApiProperty({
    required: false,
    enum: EnumB2bSubmissionGogetaStatus,
  })
  @IsEnum(EnumB2bSubmissionGogetaStatus)
  @IsOptional()
  @Field(() => EnumB2bSubmissionGogetaStatus, {
    nullable: true,
  })
  status?: "Option1" | "Asdasdsdasd" | "Asdasd" | "Asasd" | "Asd" | null;
}

export { B2bSubmissionGogetaCreateInput as B2bSubmissionGogetaCreateInput };
