/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { B2bSubmissionGogetaWhereInput } from "./B2bSubmissionGogetaWhereInput";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";

@InputType()
class B2bSubmissionGogetaListRelationFilter {
  @ApiProperty({
    required: false,
    type: () => B2bSubmissionGogetaWhereInput,
  })
  @ValidateNested()
  @Type(() => B2bSubmissionGogetaWhereInput)
  @IsOptional()
  @Field(() => B2bSubmissionGogetaWhereInput, {
    nullable: true,
  })
  every?: B2bSubmissionGogetaWhereInput;

  @ApiProperty({
    required: false,
    type: () => B2bSubmissionGogetaWhereInput,
  })
  @ValidateNested()
  @Type(() => B2bSubmissionGogetaWhereInput)
  @IsOptional()
  @Field(() => B2bSubmissionGogetaWhereInput, {
    nullable: true,
  })
  some?: B2bSubmissionGogetaWhereInput;

  @ApiProperty({
    required: false,
    type: () => B2bSubmissionGogetaWhereInput,
  })
  @ValidateNested()
  @Type(() => B2bSubmissionGogetaWhereInput)
  @IsOptional()
  @Field(() => B2bSubmissionGogetaWhereInput, {
    nullable: true,
  })
  none?: B2bSubmissionGogetaWhereInput;
}
export { B2bSubmissionGogetaListRelationFilter as B2bSubmissionGogetaListRelationFilter };
