/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { B2bSubmissionGogetaCreateInput } from "./B2bSubmissionGogetaCreateInput";
import { ValidateNested } from "class-validator";
import { Type } from "class-transformer";

@ArgsType()
class CreateB2bSubmissionGogetaArgs {
  @ApiProperty({
    required: true,
    type: () => B2bSubmissionGogetaCreateInput,
  })
  @ValidateNested()
  @Type(() => B2bSubmissionGogetaCreateInput)
  @Field(() => B2bSubmissionGogetaCreateInput, { nullable: false })
  data!: B2bSubmissionGogetaCreateInput;
}

export { CreateB2bSubmissionGogetaArgs as CreateB2bSubmissionGogetaArgs };
